{
 "title": "Overview",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Disk Usage (Max)",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum (max_over_time(kafka_log_Log_Value{name='Size'}[15m])) by (instance)"
    },
    {
     "expr": "sum (max_over_time(kafka_log_Log_Value{name='NumLogSegments'}[15m])) by (instance)"
    }
   ]
  },
  {
   "title": "Offline",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kafka_controller_KafkaController_Value{name=\"OfflinePartitionsCount\"})"
    }
   ]
  },
  {
   "title": "Under-replicated",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kafka_server_ReplicaManager_Value{name=\"UnderReplicatedPartitions\"})"
    }
   ]
  },
  {
   "title": "Active",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_Value{name=\"ActiveControllerCount\"}"
    }
   ]
  },
  {
   "title": "Handlers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(kafka_server_KafkaRequestHandlerPool_OneMinuteRate{name=\"RequestHandlerAvgIdlePercent\"}*100)  "
    }
   ]
  },
  {
   "title": "ZooKeeper Session Expires / hour",
   "type": "graph",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_SessionExpireListener_FiveMinuteRate{name=\"ZooKeeperExpiresPerSec\"}*3600"
    }
   ]
  },
  {
   "title": "Part. Imbalance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "stddev(sum(kafka_server_ReplicaManager_Value{name=\"PartitionCount\"}) by(instance))"
    }
   ]
  },
  {
   "title": "Leader Imbalance",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "stddev(sum(kafka_server_ReplicaManager_Value{name=\"LeaderCount\"}) by(instance))"
    }
   ]
  },
  {
   "title": "Network Processors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 2 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(round(kafka_network_SocketServer_Value{name=\"NetworkProcessorAvgIdlePercent\"}*100))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage (Over Time)",
   "type": "graph",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_log_Log_Value{name='Size'}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In/Out Per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 9, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (round(kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"BytesInPerSec\", job=\"kafka\", topic!=\"\"})) ",
     "legendFormat": "IN"
    },
    {
     "expr": "sum (round(-1*kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"BytesOutPerSec\", job=\"kafka\", topic!=\"\"})) ",
     "legendFormat": "OUT"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum without(area)(jvm_memory_bytes_used{job=\"kafka\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Mem.Pool",
   "type": "graph",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_network_SocketServer_Value{name=\"MemoryPoolAvailable\"})"
    },
    {
     "expr": "sum(kafka_network_SocketServer_Value{name=\"MemoryPoolUsed\"})"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 7 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response Send Time (99th percentile)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 10, "x": 9, "y": 9 },
   "targets": [
    {
     "expr": "kafka_network_RequestMetrics_99thPercentile{name=\"ResponseSendTimeMs\"}"
    }
   ]
  },
  {
   "title": "Max Replica Lag",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max(kafka_server_ReplicaFetcherManager_Value{name=\"MaxLag\"})"
    }
   ]
  },
  {
   "title": "Max Replica Lag",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 11 },
   "targets": [
    {
     "expr": "max(kafka_server_ReplicaFetcherManager_Value{name=\"MaxLag\"}) by (instance)"
    }
   ]
  }
 ]
}