{
 "title": "Topics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Topic",
    "query": "label_values(kafka_log_Log_Value, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Messages IN per Second",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum (round(kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"MessagesInPerSec\", job=\"kafka\", topic=~\"$Topic\"})) by (instance)",
     "legendFormat": "IN:{{instance}}"
    }
   ]
  },
  {
   "title": "Num.Consumers",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(sum(kafka_consumer_Group_Value{topic=\"test\"}) by (group))"
    }
   ]
  },
  {
   "title": "Partition Size Over Time",
   "type": "graph",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_log_Log_Value{job=\"kafka\",name=\"Size\", topic=~\"$Topic\"}) by (topic, partition  )",
     "legendFormat": "{{topic}}-{{partition}}"
    }
   ]
  },
  {
   "title": "Log Files Per Partition",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum (avg_over_time(kafka_log_Log_Value{name=\"Size\", topic=~\"$Topic\"}[15m])) by (topic, partition)"
    },
    {
     "expr": "sum (avg_over_time(kafka_log_Log_Value{name=\"NumLogSegments\", topic=~\"$Topic\"}[15m])) by (topic, partition)"
    }
   ]
  },
  {
   "title": "Bytes IN/OUT per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (round(kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"BytesInPerSec\", job=\"kafka\", topic=~\"$Topic\"})) by (instance)",
     "legendFormat": "IN:{{instance}}"
    },
    {
     "expr": "sum (-1 * round(kafka_server_BrokerTopicMetrics_OneMinuteRate{name=\"BytesInPerSec\", job=\"kafka\", topic=~\"$Topic\"})) by (instance)",
     "legendFormat": "OUT:{{instance}}"
    }
   ]
  }
 ]
}