{
 "title": "Consumer Groups",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Group",
    "query": "label_values(kafka_consumer_Group_Value{name=\"ConsumerOffset\"}, group)"
   },
   {
    "name": "Topics",
    "query": "label_values(kafka_consumer_Group_Value{name=\"ConsumerLag\", group=\"$Group\"}, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Consumer Lag",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum  without(instance)(kafka_consumer_Group_Value{name=\"ConsumerLag\", group=\"$Group\", job=\"kafka\",topic=~\"$Topics\"})   ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{topic}}-{{partition}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consumer Max Lag",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "max (kafka_consumer_Group_Value{name=\"ConsumerLag\", group=\"$Group\", job=\"kafka\",topic=~\"$Topics\"})   "
    }
   ]
  },
  {
   "title": "Consumer Offsets",
   "type": "graph",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(kafka_consumer_Group_Value{name=\"ConsumerOffset\", group=\"$Group\", job=\"kafka\",topic=~\"$Topics\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{toipic}}-{{partition}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Lag Trend",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "max(kafka_consumer_Group_Value{name=\"ConsumerLag\", group=\"$Group\", job=\"kafka\",topic=~\"$Topics\"}) by (topic, partition)"
    }
   ]
  },
  {
   "title": "Log End Offsets",
   "type": "graph",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(kafka_log_Log_Value{name=\"LogEndOffset\", job=\"kafka\",topic=~\"$Topics\"})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{topic}}-{{partition}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}