#!/bin/bash

/opt/kafka/current/bin/kafka-console-consumer.sh \
    --consumer.config /usr/sbin/kafka.properties \
    --bootstrap-server $KAFKA_INTERNAL_CONNECTION \
    --property schema.registry.url=$SCHEMA_REGISTRY_INTERNAL_URL "$@"
