#!/usr/bin/env bash

ADMIN_PASSWORD="admin"

HOST1=172.17.0.2

GIT_SERVER=$HOST1

ZK_SERVERS=($HOST1)

SCHEMA_REGISTRY_HOST=$HOST1
AVRO_COMPATIBILITY_LEVEL=full_transitive

KAFKA_SERVERS=($HOST1)
KAFKA_ADVERTISED_HOSTS=(localhost)
KAFKA_PROTOCOL="PLAINTEXT"
KAFKA_REPL_FACTOR=1
KAFKA_MEMORY_BUFFER=1073741824
KAFKA_SASL_MECHANISM=PLAIN
KAFKA_AUTHORIZER_CLASS_NAME=kafka.security.auth.SimpleAclAuthorizer

GRAFANA_SERVER=$HOST1
GRAFANA_EDITABLE="true"

PROMETHEUS_SERVERS=($HOST1)
PROMETHEUS_RETENTION=7d
