#!/usr/bin/env bash

KAFKA_VERSION=2.0.0
CF_VERSION=5.0.0

SERVICES=(
    "cd"
    "gitd"
    "zookeeper"
    "kafka"
    "kafka-topics"
    "schema-registry"
    "grafana"
    "prometheus"
)

HOST1=172.17.0.2

#Get Server
GIT_SERVER=$HOST1
GIT_SERVER_DATA_DIR=/data/git



#Zookeeper
ZK_SERVERS=($HOST1)
ZOOKEEPER_PORT=2181

#Schema Registry
SCHEMA_REGISTRY_HOST=$HOST1
SCHEMA_REGISTRY_PORT=8081
AVRO_COMPATIBILITY_LEVEL=full_transitive

#Kafka Broker
KAFKA_SERVERS=($HOST1)
KAFKA_ADVERTISED_HOSTS=(localhost)
KAFKA_LOG_DIRS="/data/kafka"
KAFKA_PROTOCOL="PLAINTEXT"
KAFKA_REPL_FACTOR=1
KAFKA_PORT=9092
#KAFKA_SASL_MECHANISM=PLAIN
#KAFKA_AUTHORIZER_CLASS_NAME=kafka.security.auth.SimpleAclAuthorizer

#Metrics
GRAFANA_SERVER=$HOST1
GRAFANA_PORT=8300
PROMETHEUS_SERVERS=($HOST1)
PROMETHEUS_DATA_DIR=/data/prometheus/
PROMETHEUS_RETENTION=7d
